engines:
  cppcheck:
    enabled: true
    config:
      check: all
      language: c++
      stds:
        - c++11
      platform: unix64
      defines:
      - "DEBUG=1"
      - "__cplusplus"
      undefines:
      - "DEBUG"
      max_configs: 42
      inconclusive: false
